version:  '3.7'
services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    container_name: cassandra
    volumes:
      - cassandra_data:/bitnami
    ports:
      - "7199:7199" # JMX
      - "7000:7000" # cluster communication
      - "7001:7001" # cluster communication (SSL)
      - "9042:9042" # native protocol clients
      - "9160:9160" # thrift clients
volumes:
  cassandra_data:
    driver: local